spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:hospital
        username:
        password: 5657
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
            show-sql: true