spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testFundamentals
        username: sa
        password: password
    h2:
        console:
            enabled: true
            path: /h2